/**
 * Email Sender Module
 * Sends the funding digest via SMTP (Gmail recommended).
 * Supports HTML + plain text multipart emails.
 */

const nodemailer = require("nodemailer");

/**
 * Send the digest email.
 */
async function sendDigestEmail(digest, config) {
  const { EMAIL_FROM, EMAIL_PASSWORD, EMAIL_TO } = config;

  if (!EMAIL_FROM || !EMAIL_PASSWORD || !EMAIL_TO) {
    throw new Error("Email config incomplete. Check EMAIL_FROM, EMAIL_PASSWORD, EMAIL_TO in .env");
  }

  const transporter = nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 465,
    secure: true,
    auth: {
      user: EMAIL_FROM,
      pass: EMAIL_PASSWORD, // Must be a Gmail App Password (not account password)
    },
  });

  const recipients = EMAIL_TO.split(",").map((e) => e.trim());

  const info = await transporter.sendMail({
    from: `"EU Funding Monitor 🇪🇺" <${EMAIL_FROM}>`,
    to: recipients.join(", "),
    subject: digest.subject,
    text: digest.body_text,
    html: wrapHtmlEmail(digest.body_html, digest.subject),
  });

  return info;
}

/**
 * Wrap the email body in a clean HTML shell.
 */
function wrapHtmlEmail(bodyHtml, subject) {
  const date = new Date().toLocaleDateString("en-GB", {
    weekday: "long", day: "2-digit", month: "long", year: "numeric"
  });

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${subject}</title>
<style>
  body { font-family: 'Helvetica Neue', Arial, sans-serif; background: #f5f5f5; margin: 0; padding: 20px; color: #1a1a2e; }
  .container { max-width: 700px; margin: 0 auto; background: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 12px rgba(0,0,0,0.08); }
  .header { background: #003087; padding: 28px 32px; }
  .header h1 { color: #ffffff; margin: 0; font-size: 20px; font-weight: 600; letter-spacing: -0.3px; }
  .header .date { color: #8ab0e8; font-size: 13px; margin-top: 4px; }
  .header .stars { color: #f0c040; font-size: 18px; margin-bottom: 8px; }
  .body { padding: 28px 32px; line-height: 1.6; }
  h2 { color: #003087; font-size: 15px; font-weight: 700; margin-top: 28px; margin-bottom: 8px; padding-bottom: 6px; border-bottom: 2px solid #e8ecf4; }
  h3 { color: #1a1a2e; font-size: 14px; font-weight: 600; margin-top: 16px; margin-bottom: 4px; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 700; letter-spacing: 0.5px; margin-right: 6px; }
  .badge-open { background: #d4edda; color: #155724; }
  .badge-upcoming { background: #fff3cd; color: #856404; }
  .badge-ongoing { background: #cce5ff; color: #004085; }
  .badge-critical { background: #f8d7da; color: #721c24; }
  ul { padding-left: 20px; margin: 8px 0; }
  li { margin-bottom: 6px; font-size: 14px; }
  p { font-size: 14px; margin: 8px 0; }
  .action-item { background: #fff8e6; border-left: 3px solid #f0c040; padding: 10px 14px; margin: 8px 0; border-radius: 0 4px 4px 0; font-size: 14px; }
  .footer { background: #f8f9fc; padding: 16px 32px; border-top: 1px solid #e8ecf4; font-size: 12px; color: #6c757d; }
  a { color: #003087; }
  strong { color: #1a1a2e; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <div class="stars">★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★</div>
    <h1>EU Funding Monitor</h1>
    <div class="date">Bavaria Yachts România — ${date}</div>
  </div>
  <div class="body">
    ${bodyHtml}
  </div>
  <div class="footer">
    Automated digest generated by EU Funding Monitor. Sources monitored span Romanian national portals, 
    EU institutions, Interreg Danube, CINEA, and specialized inland waterway programmes.<br>
    Verify all deadlines independently before acting. EU funding terms change.
  </div>
</div>
</body>
</html>`;
}

module.exports = { sendDigestEmail };
